module.exports = {
  parserOptions: {
    ecmaVersion: 7,
    ecmaFeatures: {
      impliedStrict: false
    }
  },
  env: {
    node: true,
    es6: true,
    mocha: true
  },
  extends: 'eslint:recommended',
  rules: {
    'no-extra-parens': [2, 'all', {
        conditionalAssign: false,
        returnAssign: false,
        nestedBinaryExpressions: false
    }],
    'no-prototype-builtins': 2,
    'no-template-curly-in-string': 2,
    'no-unsafe-negation': 2,
    'valid-jsdoc': 2,

    'accessor-pairs': 2,
    'array-callback-return': 2,
    'class-methods-use-this': 2,
    complexity: 2,
    'consistent-return': 1,
    curly: 2,
    'default-case': 2,
    'dot-location': [2, 'property'],
    'dot-notation': 2,
    eqeqeq: 2,
    'guard-for-in': 1,
    'no-alert': 2,
    'no-caller': 2,
    'no-case-declarations': 0,
    'no-div-regex': 2,
    'no-else-return': 2,
    'no-empty-function': 2,
    'no-eq-null': 0,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-label': 2,
    'no-floating-decimal': 2,
    'no-global-assign': 2,
    'no-implicit-coercion': [2, { allow: ['!!'] } ],
    'no-implicit-globals': 2,
    'no-implied-eval': 2,
    'no-invalid-this': 0, // set to error in browser environment
    'no-iterator': 2,
    'no-labels': 0,
    'no-lone-blocks': 2,
    'no-loop-func': 1,
    'no-magic-numbers': 0,
    'no-multi-spaces': 2,
    'no-multi-str': 2,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-new': 2,
    'no-octal-escape': 2,
    'no-octal': 2,
    'no-param-reassign': 1,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-return-assign': 2,
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-unmodified-loop-condition': 1,
    'no-unused-expressions': 0,
    'no-unused-labels': 2,
    'no-useless-call': 2,
    'no-useless-concat': 2,
    'no-useless-escape': 2,
    'no-void': 2,
    'no-warning-comments': 1,
    'no-with': 2,
    radix: 2,
    'vars-on-top': 0,
    'wrap-iife': 0,
    yoda: 2,

    strict: [2, 'safe'],

    'init-declaration': 0,
    'no-catch-shadow': 2,
    'no-delete-var': 2,
    'no-label-var': 2,
    'no-restricted-globals': 2,
    'no-shadow-restricted-names': 2,
    'no-shadow': 2,
    'no-undef-init': 2,
    'no-undef': 2,
    'no-undefined': 0, // No shadow possible with other rules
    'no-unused-vars': 2,
    'no-use-before-define': 2,

    // Node JS Part
    'callback-return': 0,
    'global-require': 2,
    'handle-callback-err': 2,
    'no-mixed-requires': 0,
    'no-new-require': 2,
    'no-path-concat': 2,
    'no-process-env': 1,
    'no-process-exit': 2,
    'no-restricted-modules': [0, 'bluebird'],
    'no-sync': 0,

    // Let s have some style
    'array-bracket-spacing': [2, 'never'],
    'block-spacing': 2,
    'brace-style': [2, '1tbs', {allowSingleLine: true}],
    camelcase: [2, {properties: 'never'}],
    'comma-dangle': [2, 'never'],
    'comma-spacing': [2, {before: false, after: true}],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'consistent-this': 0,
    'eol-last': 2,
    'func-call-spacing': [2, 'never'],
    'func-names': 0,
    'func-style': 0,
    'id-blacklist': 0,
    'id-length': 0,
    'id-match': 0,
    indent: [2, 2, {
      SwitchCase: 1,
      MemberExpression: 1
    }],
    'jsx-quotes': 0,
    'key-spacing': [2, {
      beforeColon: false,
      afterColon: true,
      mode: 'strict'
    }],
    'keyword-spacing': [2, {
      before: true,
      after: true
    }],
    'linebreak-style': [2, 'unix'],
    'lines-around-comment': 0,
    'max-depth': [1, { max: 10}],
    'max-len': [2, 1000],
    'max-lines': [2, 1000],
    'max-nested-callbacks': 0, // We use max-depth instead
    'max-params': [2, {max: 10}],
    'max-statements-per-line': [2, {max: 2}],
    'max-statements': 0,
    'multiline-ternary': 0,
    'new-cap': 2,
    'new-parens': 2,
    'newline-after-var': 0,
    'newline-before-return': 0,
    'newline-per-chained-call': 2,
    'no-array-constructor': 2,
    'no-bitwise': 2,
    'no-continue': 0,
    'no-inline-comments': 0,
    'no-lonely-if': 2,
    'no-mixed-operator': 0,
    'no-multiple-empty-lines': [2, {max: 2, maxEOF: 1 }],
    'no-negated-condition': 2,
    'no-nested-ternary': 0,
    'no-new-object': 2,
    'no-plusplus': 0,
    'no-restricted-syntax': 0,
    'no-tabs': 2,
    'no-ternary': 0,
    'no-trailing-spaces': 2,
    'no-underscore-dangle': 0,
    'no-unneeded-ternary': 2,
    'no-whitespace-before-property': 2,
    'object-curly-newline': [2, {multiline: true}],
    'object-curly-spacing': [2, 'never'],
    'object-property-newline': 0,
    'one-var-declaration-per-line': 0,
    'one-var': [2, 'never'],
    'operator-assignment': [1, 'always'],
    'operator-linebreak': [2, 'before', {overrides: {'=': 'none'}}],
    'padded-blocks': [2, 'never'],
    'quote-props': [2, 'as-needed'],
    quotes: [2, 'single'],
    'require-jsdoc': 1,
    'semi-spacing': [2, {before: false, after: true}],
    semi: [2, 'always'],
    'sort-keys': 0,
    'sort-vars': 0,
    'space-before-blocks': 2,
    'space-before-function-paren': [2, 'never'],
    'space-in-parens': [2, 'never'],
    'space-infix-ops': 2,
    'space-unary-ops': [2, {words: true, nonwords: false}],
    'spaced-comment': 0,
    'unicode-bom': [2, 'never'],
    'wrap-regex': 0,

    // ESNext feature
    'arrow-body-style': 0,
    'arrow-parens': [2, 'as-needed'],
    'arrow-spacing': [2, {before: true, after: true}],
    'generator-star-spacing': [2, {before: false, after: true}],
    'no-confusing-arrow': 2,
    'no-duplicate-imports': 2,
    'no-restricted-imports': 0,
    'no-useless-computed-key': 2,
    'no-useless-constructor': 2,
    'no-useless-rename': 2,
    'no-var': 2,
    'object-shorthand': 2,
    'prefer-arrow-callback': [1, { 'allowNamedFunctions': true }],
    'prefer-const': 2,
    'prefer-reflect': 0,
    'prefer-rest-params': 2,
    'prefer-spread': 0,
    'prefer-template': 2,
    'require-yield': 0,
    'rest-spread-spacing': [2, 'never'],
    'sort-imports': 0,
    'symbol-description': 1,
    'template-curly-spacing': [2, 'never'],
    'yield-star-spacing': [2, 'after']
  }
};
